# Generated by Django 2.0.5 on 2018-08-09 17:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('django_comments', '0004_comment_votes'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='has_downvoted',
            field=models.ManyToManyField(related_name='people_that_downvoted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comment',
            name='has_updated',
            field=models.ManyToManyField(related_name='people_that_upvoted', to=settings.AUTH_USER_MODEL),
        ),
    ]
