# Generated by Django 2.0.5 on 2018-08-09 17:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_comments', '0005_auto_20180809_1047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='has_downvoted',
            field=models.ManyToManyField(blank=True, related_name='people_that_downvoted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='comment',
            name='has_updated',
            field=models.ManyToManyField(blank=True, related_name='people_that_upvoted', to=settings.AUTH_USER_MODEL),
        ),
    ]
