# Generated by Django 2.0.5 on 2018-08-13 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_comments', '0006_auto_20180809_1049'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='has_updated',
            new_name='has_upvoted',
        ),
    ]
