# Generated by Django 2.1.7 on 2019-03-16 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_topic_next_topic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='next_topic',
        ),
        migrations.AddField(
            model_name='concept',
            name='order_in_topic',
            field=models.IntegerField(null=True, unique=True),
        ),
        migrations.AddField(
            model_name='topic',
            name='order_in_subject',
            field=models.IntegerField(null=True, unique=True),
        ),
    ]
