# Generated by Django 2.1.7 on 2019-03-16 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20190316_0955'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='concept',
            name='order_in_topic',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='order_in_subject',
        ),
    ]
