# Generated by Django 2.1.7 on 2019-03-16 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20190316_1001'),
    ]

    operations = [
        migrations.AddField(
            model_name='concept',
            name='order_in_topic',
            field=models.IntegerField(null=True, unique=True),
        ),
        migrations.AddField(
            model_name='topic',
            name='order_in_subject',
            field=models.IntegerField(null=True, unique=True),
        ),
    ]
