# Generated by Django 2.1.7 on 2019-03-16 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20190316_1002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concept',
            name='order_in_topic',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='topic',
            name='order_in_subject',
            field=models.IntegerField(null=True),
        ),
    ]
