# Generated by Django 2.1.7 on 2019-03-26 22:27

import constrainedfilefield.fields.file
from django.db import migrations
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20190325_2133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='upload',
            field=constrainedfilefield.fields.file.ConstrainedFileField(content_types=['video/mp4'], default='', max_upload_size=5000000000, mime_lookup_length=4096, upload_to=main.models.user_directory_path, verbose_name='upload'),
        ),
    ]
