# Generated by Django 2.1.7 on 2019-03-27 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20190326_1527'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='resource',
            unique_together={('creator', 'title')},
        ),
    ]
