# Generated by Django 2.1.7 on 2019-03-27 22:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20190327_1453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='title',
            field=models.CharField(default=datetime.datetime.now, max_length=100, verbose_name='title'),
        ),
    ]
