# Generated by Django 2.1.7 on 2019-03-28 20:00

import constrainedfilefield.fields.file
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20190327_1503'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemporaryFileStorage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='temp', max_length=100)),
                ('temp_upload', constrainedfilefield.fields.file.ConstrainedFileField(content_types=['video/mp4'], default='', max_upload_size=5000000000, mime_lookup_length=4096, upload_to=main.models.user_directory_path, verbose_name='temp upload')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='creator')),
            ],
        ),
    ]
