# Generated by Django 2.1.7 on 2019-03-30 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_temporaryfilestorage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='temporaryfilestorage',
            old_name='temp_upload',
            new_name='upload',
        ),
    ]
