# Generated by Django 2.1.7 on 2019-04-01 23:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_auto_20190330_0938'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='upload_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
